// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4I4k1M7rxCc-630dzd2DMpoo4axtrYFQ',
    appId: '1:244704747666:android:7d009574ea350a356c064b',
    messagingSenderId: '244704747666',
    projectId: 'laasociacion-57649',
    databaseURL: '[https://laasociacion-57649-default-rtdb.firebaseio.com](https://laasociacion-57649-default-rtdb.firebaseio.com)',
    storageBucket: 'laasociacion-57649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDyUYUWhV7U1vwvuPeNSo-9Chcgg3aN4',
    appId: '1:244704747666:ios:37e4e57584edbda06c064b',
    messagingSenderId: '244704747666',
    projectId: 'laasociacion-57649',
    databaseURL: '[https://laasociacion-57649-default-rtdb.firebaseio.com](https://laasociacion-57649-default-rtdb.firebaseio.com)',
    storageBucket: 'laasociacion-57649.appspot.com',
    iosBundleId: 'com.example.theRingPrivateFlutter',
  );
}
